name: CI

on:
  push:
    branches: [main, setup-task]
  pull_request:
    branches: [main, setup-task]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test import
        run: |
          python -c "import pandas, numpy, matplotlib, seaborn"
